# Generated by Django 3.2.7 on 2021-09-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=50)),
                ('vaccinated', models.CharField(max_length=50)),
                ('emergency_contact_name', models.CharField(max_length=250)),
                ('emergency_contact_phone', models.CharField(max_length=100)),
                ('qr_code', models.CharField(max_length=1000)),
            ],
        ),
    ]
