# Generated by Django 3.2.7 on 2021-09-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_player_registeration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
