# Generated by Django 3.2.7 on 2021-09-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_player_player_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
