# Generated by Django 3.2.7 on 2021-09-27 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_auto_20210927_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_pic',
            new_name='profile_picture',
        ),
    ]
