# Generated by Django 3.2.7 on 2021-09-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_auto_20210927_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='qr_code',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
