# Generated by Django 3.2.7 on 2021-09-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0007_alter_player_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
