# Generated by Django 3.2.7 on 2021-09-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0008_alter_player_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='vaccinated',
            field=models.BooleanField(default=False),
        ),
    ]
