# Generated by Django 3.2.7 on 2021-09-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0010_alter_player_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='disclaimer',
            field=models.BooleanField(default=False),
        ),
    ]
