# Generated by Django 3.2.7 on 2021-10-01 08:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0011_player_disclaimer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateField(default=datetime.date.today)),
                ('scan_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.player')),
            ],
        ),
    ]
