# Generated by Django 3.2.7 on 2021-10-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0012_daily_scan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_scan',
            old_name='player_id',
            new_name='player',
        ),
    ]
