# Generated by Django 3.2.7 on 2021-10-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0013_rename_player_id_daily_scan_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='qr_code',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
