# Generated by Django 3.2.7 on 2021-10-05 21:33

from django.db import migrations, models
import sport.models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0014_alter_player_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='plus21',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(default='', upload_to=sport.models.rename_profile_image),
        ),
    ]
