# Generated by Django 3.2.7 on 2021-10-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0015_auto_20211005_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='qr_code',
            field=models.CharField(max_length=20),
        ),
    ]
