# Generated by Django 3.2.7 on 2021-12-18 02:58

from django.db import migrations, models
import sport.models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0018_auto_20211009_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_scan',
            name='scan_date',
            field=models.CharField(default=sport.models.get_cst_date, max_length=50),
        ),
        migrations.AlterField(
            model_name='daily_scan',
            name='scan_timestamp',
            field=models.DateTimeField(default=sport.models.get_cst_timestamp),
        ),
        migrations.AlterField(
            model_name='player',
            name='registeration_date',
            field=models.DateTimeField(default=sport.models.get_cst_timestamp),
        ),
    ]
