# Generated by Django 3.2.7 on 2021-12-18 02:59

from django.db import migrations, models
import sport.models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0020_alter_daily_scan_scan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_scan',
            name='scan_date',
            field=models.CharField(default=sport.models.get_cst_date, max_length=50),
        ),
    ]
