# Generated by Django 3.2.7 on 2021-12-19 16:53

from django.db import migrations, models
import sport.models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0024_auto_20211219_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_scan',
            name='scan_date',
            field=models.CharField(default=sport.models.get_cst_date, max_length=50),
        ),
        migrations.AlterField(
            model_name='daily_scan',
            name='scan_timestamp',
            field=models.CharField(default=sport.models.get_cst_timestamp, max_length=100),
        ),
    ]
